[versions]
changelog = "2.5.0"
intelliJPlatform = "2.11.0"
kotlin = "2.3.0"
qodana = "2025.3.1"

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
